### ISSUE TITLE
Shaderpacks do not show the manual download suggestion

### ISSUE THREAD

**Issue by TLATER** [packwiz/packwiz-installer#48]
Hi, I'm trying to add [Sildur's vibrant shaders](https://www.curseforge.com/minecraft/customization/sildurs-vibrant-shaders) to my modpack; AIUI, curseforge in general does not permit accessing shader packs via their API, so the automated downloads generally fail for this, and I need to create the meta files manually because `packwiz curseforge add` and `packwiz url add` both fail:

```toml
name = "Sildur's Vibrant Shaders Extreme VL"
filename = "Sildur's Vibrant Shaders v1.41 Extreme-VL.zip"
side = "client"

[download]
hash-format = "sha1"
hash = "04be53a2b289cbf51830fbff7a5442c3c8c460b3"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4019719
project-id = 544096
```

So far this is mostly expected, and writing these files by hand isn't too much effort (though I suppose there's a packwiz enhancement ticket in here somewhere).

However, when using `packwiz-install`, I would expect a pop-up telling users to download the files manually, just like with mods that don't permit API access. All metadata for this should be present, after all. Instead I get a cryptic error:

![2022-12-31T17:16:04](https://user-images.githubusercontent.com/6654841/210150981-dd0c1985-53de-4d3a-ac6a-da2848770fd5.png)

It's a bit of a shame, this would be a really nice way to work around the limitations of the curseforge pack format, and still help people get their shaders installed (and updated, in case of the many, many rendering issues they often cause...). All while being perfectly compliant copyright-wise and giving proper attribution and ad clicks.
