### ISSUE TITLE
Mods with side: "both" are not installed on client

### ISSUE THREAD

**Issue by xtexChooser** [packwiz/packwiz-installer#54]
As the title, `"$INST_JAVA" -jar packwiz-installer-bootstrap.jar http://127.0.0.1:8080/pack.toml` will not install mods with `side = "both"` without `--side both`.

```toml
name = "bad packets"
filename = "badpackets-fabric-0.3.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ftdbN0KK/versions/9hA9pLHz/badpackets-fabric-0.3.4.jar"
hash-format = "sha1"
hash = "d65faf486a088e1a706b29457f6b1725665a8379"

[update]
[update.modrinth]
mod-id = "ftdbN0KK"
version = "9hA9pLHz"

```
